version: '3.8'
services:
  blog-syahid:
    container_name: blog-syahid
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_H2_CONSOLE_ENABLED: 'true'
    depends_on:
      - h2-database

  h2-database:
    image: "buildo/h2database"
    ports:
      - "9090:8082"  # Expose H2 console on port 9090
    environment:
      - H2_OPTIONS=-ifNotExists